# This is a basic workflow to help you get started with Actions

name: CI

on: push

jobs:
  code_quality:
    runs-on: ubuntu-latest
    name: Tests
    container: python:3.7

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Checkout code
        run: |
          apt update
          apt install -y wget software-properties-common lsb-release gcc make python3 python3-pip python3-dev libsasl2-modules-gssapi-mit krb5-user
          wget -qO - https://packages.confluent.io/deb/7.0/archive.key | apt-key add -
          add-apt-repository "deb https://packages.confluent.io/clients/deb $(lsb_release -cs) main"
          apt install -y librdkafka-dev
          python3 -m pip install --no-binary confluent-kafka confluent-kafka
          python3 -c 'import confluent_kafka; print(confluent_kafka.version())'
      - name: Run tests
        run: |
          pip install -r requirements-dev.txt
          ls -la
          pytest --doctest-modules