# This is a basic workflow to help you get started with Actions

name: CI

on: push

jobs:
  code_quality:
    runs-on: ubuntu-latest
    name: Tests
    container: python:3.9

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Configure container
        run: |
          export DEBIAN_FRONTEND=noninteractive
          apt-get update
          apt-get upgrade -y
          apt-get install -y wget software-properties-common lsb-release gcc make python3 python3-pip python3-dev libsasl2-modules-gssapi-mit
          apt-get -yqq install krb5-user libpam-krb5
          apt-get -yqq clean
          wget -qO - https://packages.confluent.io/deb/7.0/archive.key | apt-key add -
          add-apt-repository "deb https://packages.confluent.io/clients/deb $(lsb_release -cs) main"
          apt-get install -y librdkafka-dev
          pip install -r requirements-dev.txt
      - name: Run tests
        run: |
          ls -la
          pytest --doctest-modules