# This is a basic workflow to help you get started with Actions

name: CI

on: push

jobs:
  code_quality:
    runs-on: ubuntu-latest
    name: Tests
    container: python:3.7.3

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure kafka
        run: |
          apt-get update
          apt-get install librdkafka
      - name: Run script
        run: |
          pip install -r requirements-dev.txt
          ls -la
          pytest --doctest-modules